# Generated by Django 3.1.7 on 2021-05-15 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191223_1445'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vacancy',
            managers=[
            ],
        ),
    ]
